services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: subscription_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      CLOUDBEAVER_FORCE_HTTPS: "false"
    ports:
      - "9091:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - postgres-db
    restart: always

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
  cloudbeaver_data:
