spring:
  application:
    name: subscription-api
  main:
    log-startup-info: false
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_db
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      pool-name: HikariJpaPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create
  devtools:
    restart:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: "V2VyeUxpbm9fUmFuZG9tX1NlY3JldF9LZXlfRm9yX1N1YnNjcmlwdGlvbl9BcGlfQXBwbGljYXRpb25fR2VuZXJhdGVkX0J5X01lX0Zvcl9TZWN1cml0eQ=="
    expiration-ms: 86400000
  security:
    token-blacklist:
      enabled: true

logging:
  level:
    root: warn
    org.springframework: warn
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: error
    org.hibernate: warn
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    se.lexicon.subscriptionapi.config.DataSeeder: info

